<div class="menu-backdrop" data-menu-backdrop hidden></div>
<aside class="app-menu" id="app-menu" aria-label="More navigation" aria-hidden="true" hidden>
    <div class="menu-header"><strong>ULTIMATE APP BORACAY</strong><button type="button" data-menu-close aria-label="Close menu" title="Close menu"><span data-icon="x"></span></button></div>
    <div class="menu-user"><span data-icon="user"></span><strong><?= e($user['full_name']) ?></strong></div>
    <nav aria-label="More">
        <div class="menu-group"><h2>Wallet</h2><a href="buy-credits.php"><span data-icon="shopping-cart"></span>Buy Credits</a><a href="convert.php"><span data-icon="refresh-cw"></span>Convert &amp; Transfer</a><a href="boracay-cash.php"><span class="cash-wallet-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="16" rx="2"/><path d="M2 9h20M16 14h6"/></svg></span>Boracay Cash</a></div>
        <div class="menu-group"><h2>Explore</h2><a href="uride.php"><span data-icon="car"></span>URide</a><a href="driver/"><span data-icon="car"></span>Drive with URide</a><a href="merchant-map.php"><span data-icon="map-pin"></span>Where to pay</a><details><summary><span data-icon="shopping-bag"></span>More services<span data-icon="chevron-right"></span></summary><div class="menu-submenu"><?php foreach (service_catalog() as $service): if ($service['code'] === 'URide') continue; ?><a href="<?= e($service['href']) ?>"><?= e($service['label']) ?></a><?php endforeach; ?></div></details></div>
        <div class="menu-group"><h2>Community</h2><a href="community.php?view=lgu"><span data-icon="home"></span>LGU Malay</a><a href="community.php?view=emergency"><span data-icon="phone"></span>Emergency</a><?php if (ubarangay_enabled()): ?><a href="ubarangay.php"><span data-icon="map-pin"></span>UBarangay</a><?php endif; ?><a href="community.php?view=barangay"><span data-icon="map-pin"></span>Barangay halls</a></div>
        <div class="menu-group"><h2>Updates</h2><a href="news.php"><span data-icon="megaphone"></span>News &amp; Updates</a><a href="notifications.php"><span data-icon="bell"></span>Notifications<?php if ($unread): ?><b class="menu-count"><?= $unread > 9 ? '9+' : $unread ?></b><?php endif; ?></a><a href="service-requests.php"><span data-icon="receipt"></span>My Requests</a><a href="support.php"><span data-icon="megaphone"></span>Help &amp; Support</a><?php if (($user['role'] ?? '') === 'mctc'): ?><a href="merchant.php"><span data-icon="qr-code"></span>MCTC Portal</a><?php endif; ?></div>
        <div class="menu-group menu-exit"><form method="post" action="logout.php"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><button type="submit"><span data-icon="log-out"></span>Log Out</button></form></div>
    </nav>
</aside>
